### ISSUE TITLE
Center Intro Video 

### ISSUE THREAD

**Issue by coke11** [coke11/yoshi123#1]
We need to center the intro video

**Comment by joker314** [comment]
Sure! You can do that in a few ways: Using a `<center>` makes the most sense. I'll make a Pull Request now! :)

**Comment by coke11** [comment]
Thank you! I just started learning HTML about a month ago. When will the Pull Request be done?

**Comment by joker314** [comment]
I just want to doublle-ceck it works before I make a PR

**Comment by coke11** [comment]
K, thank you!

**Comment by joker314** [comment]
K, pull request made :)

**Comment by coke11** [comment]
Merged

**Comment by joker314** [comment]
So Issue Closed?

**Comment by coke11** [comment]
Yep!
