### ISSUE TITLE
A bit more CSS

### ISSUE THREAD

**Issue by joker314** [coke11/yoshi123#4]
The white background is nice and all, but I was thinking that a bit of styling wouldn't hurt? What does Yoshi 123 think?

**Comment by coke11** [comment]
Yes, his channel color is red so maybe we could do a dark red? I am texting him now so I can see. Also you can call him Yoshi, or Caleb.

**Comment by coke11** [comment]
Ok lol I asked him. This is what I said 

> yes. You know how you’re site has a white backdrop? Do you think we could make it red and you would like it (By the way please respond with the letters the right way, not backwards so it is faster)

he replied

> yo!

Edit: I asked him to be serious and he said he thinks orange will look nice.

**Comment by joker314** [comment]
Ok, so a dark red? Sounds good. Would you still be able to read the text though?

**Comment by coke11** [comment]
No. View the latest post

**Comment by joker314** [comment]
So normal red (`#ff0000`)?

**Comment by coke11** [comment]
No, he wants orange now. Read the edit.

**Comment by joker314** [comment]
Ok, I'll make PR

**Comment by coke11** [comment]
For orange?

**Comment by joker314** [comment]
Yup

**Comment by coke11** [comment]
I think he just wants normal orange btw

**Comment by joker314** [comment]
Just like `style: orange;` I assume

**Comment by coke11** [comment]
yep

**Comment by joker314** [comment]
PR has been made; pending merge

**Comment by coke11** [comment]
Thx! I have the automatic merge, so I did that.

**Comment by coke11** [comment]
Sorry about spelling mistakes
